### ISSUE TITLE
New Name?

### ISSUE THREAD

**Issue by SachaG** [studiointeract/react-accounts-ui#1]
I feel like this name might conflict with https://atmospherejs.com/alt/react-accounts-ui

Since this hasn't been published to Atmosphere yet, maybe you could change the name? Or else, maybe merge both projects somehow?

**Comment by timbrandin** [comment]
There being another project with the same name just tells me it is a good choice, it will be very easy to find! :dancer:

**Comment by timbrandin** [comment]
Closing this, now that  we've released it.
