### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getElementsByTagName' of null

### ISSUE THREAD

**Issue by SachaG** [studiointeract/react-accounts-ui#3]
Here: 

https://github.com/studiointeract/react-accounts-ui/blob/master/imports/ui/components/Field.jsx#L10

```
Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
```

**Comment by timbrandin** [comment]
Thx for noting this,
I've patched the code with 93aa51be9ad580297e872c0e59d74120207997a6, which is also released together with `1.0.7`
