### ISSUE TITLE
How to extend for user profile

### ISSUE THREAD

**Issue by radzom** [studiointeract/react-accounts-ui#5]
Hi great work you did already.
What I am missing is a way to ask user for firstname, lastname, etc... during signup and store these values in his profile.

I already figured out how to add the appropriate fields in the signup form like this

```
class NewLogin extends Accounts.ui.LoginForm {
    fields() {
        const { formState } = this.state;
        if (formState == STATES.SIGN_UP) {
            return { 
                firstname: {
                    id: 'firstname',
                    hint: 'Enter firstname',
                    label: 'firstname',
                    onChange: this.handleChange.bind(this, 'firstname')        
                },
                ...super.fields()
            };
        }
        return super.fields();
    }
}

```
But i cannot figure out how to get them into the options Object when calling the createUser method in line 451 of the LoginForm

`Accounts.createUser(options, (error) => {`

Can you give advice on it if possible at all or add a possibility for it.

Thx in advance

**Comment by timbrandin** [comment]
I've have some thoughts about this, the issue in hand is that I'd like this to tie together with a SimpleSchema on the "users" collection, but if you have a strong argument for it not to tie together, I might change my mind.

Though you're almost there with your solution, you probably want to use one of the hooks to set the data on the user correctly, have a look at the **preSignUpHook** in [`accounts_ui.js`](https://github.com/studiointeract/react-accounts-ui/blob/master/imports/accounts_ui.js) – I haven't had time to document all the hooks yet.

Tell me how it goes.

**Comment by timbrandin** [comment]
The implementation should work just like UserAccounts preSignUpHook, but I have also not yet tested to add extra fields, which I have in my backlog.

**Comment by timbrandin** [comment]
I've published a new version that supports extending the options (`release-1.0.10`)

How about something like this:

```javascript
class NewLogin extends Accounts.ui.LoginForm {
  fields() {
    const { formState } = this.state;
    if (formState == STATES.SIGN_UP) {
      return { 
        firstname: {
          id: 'firstname',
          hint: 'Enter firstname',
          label: 'firstname',
          onChange: this.handleChange.bind(this, 'firstname')
        },
        ...super.fields()
      };
    }
    return super.fields();
  }

  signUp(options = {}) {
    const { firstname = null } = this.state;
    if (firstname !== null) {
      options.profile = Object.assign(options.profile || {}, { 
        firstname: firstname
      });
    }
    super.signUp(options);
  }
}
```

Could you confirm that that works, and I'll adjust the new example in the README.

**Comment by timbrandin** [comment]
@radzom when you confirm, I'll close this.

**Comment by radzom** [comment]
thx for fast response. looks promising. will test it and give feedback later today.

And preSignUpHook was also the way for me to go.

**Comment by radzom** [comment]
works fine for me.

Just one final remark. I am using  (on server)

```
import { Accounts } from 'meteor/accounts-base';

Accounts.onCreateUser(function (options, user) {
  user.profile = options.profile || {};
  user.roles = {};
  return user;
});
```

No need for me to use preSignUpHook.

Issue can be closed

**Comment by timbrandin** [comment]
Perfect, I'll add it to the docs.
