### ISSUE TITLE
Crash when launching the app just after this package install

### ISSUE THREAD

**Issue by maz-dev** [studiointeract/react-accounts-ui#6]
Here's the stack trace. I'll try to investigate.
`W20160330-23:33:15.732(2)? (STDERR)
W20160330-23:33:15.732(2)? (STDERR) /Users/maz-dev/.meteor/packages/meteor-tool/.1.3.0_3.3ma3kz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160330-23:33:15.732(2)? (STDERR)             				throw(ex);
W20160330-23:33:15.732(2)? (STDERR)             				      ^
W20160330-23:33:15.823(2)? (STDERR) TypeError: Cannot set property 'loginNoPassword' of undefined
W20160330-23:33:15.823(2)? (STDERR)     at meteorInstall.node_modules.meteor.studiointeract:react-accounts-ui.imports.api.server.loginWithoutPassword.js (packages/studiointeract:react-accounts-ui/imports/api/server/loginWithoutPassword.js:87:1)
W20160330-23:33:15.823(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160330-23:33:15.823(2)? (STDERR)     at require (packages/modules-runtime.js:92:16)
W20160330-23:33:15.824(2)? (STDERR)     at meteorInstall.node_modules.meteor.studiointeract:react-accounts-ui.main_server.js (packages/studiointeract:react-accounts-ui/main_server.js:5:1)
W20160330-23:33:15.824(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160330-23:33:15.824(2)? (STDERR)     at require (packages/modules-runtime.js:92:16)
W20160330-23:33:15.825(2)? (STDERR)     at /Users/maz-dev/code/saintejs/.meteor/local/build/programs/server/packages/studiointeract_react-accounts-ui.js:24855:15
W20160330-23:33:15.825(2)? (STDERR)     at /Users/maz-dev/code/saintejs/.meteor/local/build/programs/server/packages/studiointeract_react-accounts-ui.js:24861:3
W20160330-23:33:15.826(2)? (STDERR)     at /Users/maz-dev/code/saintejs/.meteor/local/build/programs/server/boot.js:283:10
W20160330-23:33:15.826(2)? (STDERR)     at Array.forEach (native)`

**Comment by maz-dev** [comment]
Ok, it was related to accounts-password package that I forgot to install, silly me. My bad.
Naive question, wouldn't it make sense to add it as a dep?

**Comment by timbrandin** [comment]
yeah, that should be a dependency right?
